name: Wii-1
on:
  push:
    branches:
    - main
jobs:
  build-wii:
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Compile
      run: |
        make -f Makefile.wii3
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Desmume-wii
        path: |
          ./*.dol
